language: c

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: &default_deps
      - texlive-latex-extra
      - texlive-science
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - help2man
      - latexmk
      - hevea
      - valgrind

# env:
#   global:
#     - VERBOSE=1

matrix:
  include:
    - os: linux
    - os: osx
    - compiler: gcc
      env: CC=gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default_deps
            - [gcc-7]

script:
  - ./bootstrap && ./configure --enable-silent-rules
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install help2man ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make check ; else make distcheck ; fi
